### ISSUE TITLE
Missing files and function

### ISSUE THREAD

**Issue by artsrun-gasparyan** [sambaker/AGS-Sample#5]
The following files seem to be missing which I'm gussing also may contain the missing function #requestOrRestartState which does not seem to exist in the project and prevents the games from working.

AGS-Client/awe-core/awe-dom.js
AGS-Client/awe-core/awe-drag.js

**Comment by sambaker** [comment]
In that case you'll need to use the vnext branch of the awe-core library which you can find here
https://github.com/sambaker/awe-core/tree/vnext

**Comment by sambaker** [comment]
Also, requestOrRestartState is in that version of state-machine.js
https://github.com/sambaker/awe-core/blob/vnext/awe-state-machine.js#L112

**Comment by artsrun-gasparyan** [comment]
That seems to help, I'll try to figure out what's causing dragging issues.
Thanks
